# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b98c5b7cba7933b39d685a0f178d682e2a3bb42c7eca17b5fa593cf1986e4c5b3b9f125fe8e39cfda5161b256f21cc998389e2bde16fe60629d67f8fef20649

test:
  secret_key_base: 74bd5a55a3ad368bf0293252030d731eba4bcdb22a99ec75c3edf85d38b17fdbf7e4501f98da10c8a4e8ae37d39cdf1a8825c5376a3d931fc23610ee4c1015f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
